#! /usr/bin/env Rscript
#
pkg <- "lme4"
pDIR <- switch((U <- Sys.getenv("USER")),
               "maechler" = "~/R/Pkgs",
               "bates"    = "~/gitR",
               "bolker"   = "~/R/pkgs/lme4git",
               "stevenwalker" = "~/Development/",
               ## default:
           {  p <- paste(getwd(), '/..', sep = '')
              warning("unknown USER ", U,". -- using pDIR=",p,
                      "\n but probably need to add yourself to 'do-roxy' script")
              p
          })
pkgPATH <- file.path(pDIR, pkg)
#
library(roxygen2)
library(methods)
if(FALSE) {
  roxygenize(pkgPATH, roclets = c("collate", "namespace"))## *NOT* using "rd"
} else {
  roxygenize(pkgPATH)## <-- also recreates *.Rd files
}
owd <- setwd(pkgPATH)
## FIX  NAMESPACE entry : useDynLib(lme4,".registration=TRUE")
ll <- readLines("NAMESPACE")
i <- grep("useDynLib", ll)
ll[i] <- gsub('"', '', ll[i])#"
writeLines(ll, "NAMESPACE")
